### PR TITLE
Remove tags from devicename

### PR DESCRIPTION
**Pull request by TomoTsuyuki**
Currently, we can add tags in the device name for TOTP.
This patch prevents adding the tags for device name.

### CODE REVIEW

**Comment by golenkovm** [comment]
Hi @TomoTsuyuki 

Can we please make sure the patch is robust against XSS attacks? As I can see there are some caveats mentioned here  https://www.php.net/manual/en/function.strip-tags.php 

Cheers,
Misha

**Comment by TomoTsuyuki** [comment]
> Hi @TomoTsuyuki
> 
> Can we please make sure the patch is robust against XSS attacks? As I can see there are some caveats mentioned here https://www.php.net/manual/en/function.strip-tags.php
> 
> Cheers, Misha

Updated by using `htmlspecialchars` function.

**Comment by danmarsden** [comment]
is there a reason the standard Moodle Api clean_param() isn't being used? - all good if there is :-)

**Comment by TomoTsuyuki** [comment]
> is there a reason the standard Moodle Api clean_param() isn't being used? - all good if there is :-)

Thanks for your suggestion.
I updated the code by `clean_param()`.

**Pull request merged**
