### PR TITLE
Align email page controls with manager

### PR DESCRIPTION
**Pull request by Peterburnett**

### CODE REVIEW

**Comment by danmarsden** [comment]
will you drop in a PR for the latest 400_STABLE branch before we merge this into the older 35_STABLE one?

**Comment by Peterburnett** [comment]
@danmarsden I planned to just cherry-pick it across once merged

**Comment by danmarsden** [comment]
It's pretty bad practice.... new code should always land in the latest branch first and then be cherry-picked to older branches IMO.

**Review by keevan — APPROVED** [review]
Changes look good to me.

I do agree with Dan, this would ideally be PR'd to the latest branch first then cherry-picked back.

**Comment by Peterburnett** [comment]
Sure. the comments reminded me that we are on a new branch structure now anyway, I mostly forgot when I wrote this last night. Ill PR it against the top level and get that merged, then revisit here. Not too worried as the branches are so well aligned right now, but no reason not to order it correctly

**Pull request merged**
