### PR TITLE
Check nosetup factor correctly so that menu displays.

### LINKED ISSUE #330: No-setup/-other Factor makes Authenticator app settings disapear
I've setup the MFA tool (in Moodle 3.9.12+) and want to offer my users the possibility to use TOTP via the Authenticator app factor. Enabling only this factor disables login at all, as the users do not have TOTP setup until now. For already logged in users (logged in before the app factor is enabled) there is an option in their personal settings to setup TOTP. But this was just a test - in reality the users are not logged in and are not able to login any more. So I've added the No-setup / No other factor, as this should solve the problem according to the documentation. Fine, they are able to login although the Auth-app-factor is also enabled, but enabling this second factor makes the link in the personal settings of the users disappear. Where can they now configure their TOTP-settings?

### LINKED ISSUE #391: Preferences link to setup MFA does not appear
Hello,

I would like users to be able to setup TOTP if they want. If they do not want, they should be able to login normally.

My problem is:
- For admins: the option "Multi-factor authentication preferences" does not appear in user preferences if there is a way to log in without needing to set up TOTP.
- For non admins: The option never appears. But they are able to access directly "/admin/tool/mfa/user_preferences.php".

How can I make so that that option appears always for all users, so they are able to setup TOTP if they want?

### PR DESCRIPTION
**Pull request by danmarsden**
Fix #330 Fix #391

### CODE REVIEW

**Comment by danmarsden** [comment]
@Peterburnett can you please take a look at this one? - I think this is the right way to fix #330 #391 instead of the method used in #382

**Comment by Peterburnett** [comment]
So my only concern here is this removes the use case where you want only a certain cohort of users to be able to use MFA. Eg administrators etc. The intent of the splitting is that you don't see the menu if you would be awarded points and able to authenticate. I agree that it is causing more headaches for some users than it might be worth...

**Comment by Peterburnett** [comment]
Hmm looks like I already thought about this a while ago and mentioned it in #382. I think this is good to go. Benefit outweighs the drawbacks.

**Review by Peterburnett — APPROVED** [review]

**Comment by danmarsden** [comment]
thanks - backported to 35_STABLE branch too.

**Pull request merged**
